### ISSUE TITLE
create a docker-compose.yaml

### ISSUE THREAD

**Issue by JuliaGlocka** [JuliaGlocka/sdk-fbanalyze#1]
- [x] service for api-eventlogger
- [x] service for api-fbanalyze
- [x] service for MongoDB

**Comment by JuliaGlocka** [comment]
- setup the mongodb, mongodb express, redis, api-eventlogger, api-fbanalyze

**Comment by JuliaGlocka** [comment]
I have finished working with the tasks, but I messed branches a bit, and added docker-compose on the README branch...

**Comment by holms** [comment]
> I have finished working with the tasks, but I messed branches a bit, and added docker-compose on the README branch...

you can always delete the branch and start all over again. 
in this case do not do anything on this ticket before I review the dockerfiles for the web services and helloworld apps.
