### ISSUE TITLE
configure traefik for docker-compose

### ISSUE THREAD

**Issue by holms** [JuliaGlocka/sdk-fbanalyze#2]
Traefik will allows to address our apps by proper endpoints without playing around with docker ports mapping.
So for example you'll be able to access api-fbanalyze project like this: fbanalyze.localhost

[Traefik](https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/)

**Comment by JuliaGlocka** [comment]
- configure mongodb, mongodb express, api-eventlogger and api-fbanalyze to use traefik

**Comment by holms** [comment]
This should be done after #1 is finished.
